tup=(1,5,6,4643,643,44,65)
print(type(tup),len(tup),tup)
tup1=(1,)
print(type(tup1))
print(tup[0])
print(tup[-1])
print(tup[2])
if 44 in tup:
    print("yes it is at",tup.index)
else:
    print("no present")    
tup2=tup[1:4]
print(tup2)   
print(tup.count(44)) 
print(tup.index) 
countries=("spain","india","austrila","lanka","itlay")
print(len(countries),type(countries),countries)
tem=list(countries)
tem.append("london")
tem.pop(2)
print(len(tem),type(tem),tem)
tup3=tuple(tem)
print(tup3)
print(tup3.count("india"))
tup4=(0,1,2,3,4,3,3,5,7)
res=tup4.index(5)
print(res)
